name: Sentinel Heartbeat

on:
  schedule:
    # Run every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch: # Allows you to click "Run Now" manually

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Call Sentinel Cron API
        run: |
          curl -I -X GET "https://sentinel-ten-gamma.vercel.app/api/cron?secret=${{ secrets.CRON_SECRET }}"